// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import MessageFormController from "./message_form_controller"
application.register("message-form", MessageFormController)

import ConversationMessagesController from "./conversation_messages_controller"
application.register("conversation-messages", ConversationMessagesController)

import TrackViewController from "./track_view_controller"
application.register("track-view", TrackViewController)
